### ISSUE TITLE
Uprade to PS 0.12 ?

### ISSUE THREAD

**Issue by delanoe** [paf31/purescript-thermite#100]
Hi,
many thanks for this great library that is very useful for our project.

Since the 0.12 upgrade we were wondering if there was any plan(s) to upgrade purescript-thermite.

There is a branch created for that purpose with my collaborator already:
https://github.com/sudhirvkumar/purescript-thermite/tree/migrate_0_12

But before going deeper, we wanted to know if there was any plan(s) or advice(s) for such target.

Many thanks in advance for your answer.

**Comment by paf31** [comment]
I'm not really maintaining this any more. I'd like to find another maintainer, but in the short term, if someone wants to make a PR to update things to 0.12 then I'll merge it and make a release.

**Comment by athanclark** [comment]
@delanoe @paf31 I just submitted a PR: https://github.com/paf31/purescript-thermite/pull/102

**Comment by athanclark** [comment]
@paf31 ping - I'd be happy to take ownership of this package if you'd be willing - my PR passes tests, and is orthogonal to the new purescript-react version.

**Comment by paf31** [comment]
@athanclark Yes, sorry for the massive delay. I've added you as collaborator on the repo. Please feel free to merge as you see fit. I'll try to answer questions if it's useful, but don't feel like you need to wait for me to reply for approval now, or anything like that.

**Comment by athanclark** [comment]
Awesome, thank you so much!!

**Comment by athanclark** [comment]
@delanoe Alright, sorry for the delay. Version v6.0.1 is stable for purs v0.12.x and react v16.x
