### ISSUE TITLE
README: defaultMain params seem incorrect

### ISSUE THREAD

**Issue by momomimachli** [paf31/purescript-thermite#104]
Hello,

In the README, it seems that the parameters used for default main are incorrect:

> main = defaultMain spec initialState "MyComponent" {}

On my machine the code doesn't compile (Type does not Unify).
Looking at the tests of thermite-dom, it seems that `cons` function is needed:
https://github.com/athanclark/purescript-thermite-dom/blob/master/test/Main.purs

Therefore, it should probably be:

> main = defaultMain spec (cons initialState) "MyComponent" {}

This has solved the issue on my machine.

**Comment by athanclark** [comment]
Ahh shoot, sorry I made this a bit hasty. I'll pull this into upstream now. Thank you!

**Comment by didiercrunch** [comment]
As far as I am concerned, the example on the readme does not work.  I am in my second hour with purescript and this readme does not help me.

1. How do I install thermite?  I have used `bower install purescript-thermite --save` knowing bower is depreciated and does not fix versions correctly.

2. The example (please do not split apart the example in multiple blocks, it is hard to copy paste and error prone) does not work.  No modification found worked.  Errors like `  Module ReactDOM was not found.` and `Module Thermite.Try was not found.`  got thrown at me.  It never compiled.

3. If I succeed to make it compile, how do I bring that code to my web browser?  Where is the `index.html`? the `style.css`? the `script.js`?  no  idea.

Just having a simple hello world in a git repo would help tremendously.
