### ISSUE TITLE
Thermite example doesnt seem to work

### ISSUE THREAD

**Issue by AidanPrehatny** [paf31/purescript-thermite#106]
thermite purescript demo repl doesnt seem to load:
http://try.purescript.org/?backend=thermite&session=0f1c20f8-957d-206b-560a-e2786193bda4

**Comment by athanclark** [comment]
hmm, I'm not sure what the issue was, because it looks like it's loading now. Can you provide more details on what was happening? Or what was resolved? Was it just magically fixed?
