### ISSUE TITLE
Difference between `ComponentClass` and `Spec` types

### ISSUE THREAD

**Issue by AKST** [paf31/purescript-thermite#14]
I was wondering what the different between the two types `ComponentClass` and `Spec` is. Can I do stuff with `Spec`s other than transforming them into `ComponentClass`?

**Comment by paf31** [comment]
The `Spec` type is the specification for the component. To be able to render it, you need to turn it into an actual component, i.e. `ComponentClass`. The lack of composability of the two is one of the biggest issues of this library at the moment IMO. I would really like to solve it, but there is an issue with how to type the way React handles "props", which is documented in some other issues.

**Comment by AKST** [comment]
Oh right, I guess that would make sense, because you when you call `React.createClass` on the JS Object that represents the Spec in react, it would becomes painful to extend the Spec?

**Comment by paf31** [comment]
Right, and the issue with `props` is that we need to support the usual attributes on HTML elements when creating components, but when embedding a 3rd party component, we need to only allow the props which that component defines.

**Comment by AKST** [comment]
Right okay that makes sense, thanks for the insight
