### ISSUE TITLE
[Question] Effects in Actions 

### ISSUE THREAD

**Issue by AKST** [paf31/purescript-thermite#16]
Apologies if this is the wrong place to ask this, but I'm trying to figure out how to use Effects in the function for `performAction` in the source below

```purescript
import Debug.Trace (trace, Trace(..))
import Control.Monad.Eff
import Control.Monad.Eff.Class

-- Thremite imports

data AppEv = AppDoNothing | AppSearch String
type AppPs = {}
type AppSt = {}
type AppEf = Eff (trace :: Trace)

performAction :: forall e. T.PerformAction AppPs AppEv (T.Action (AppEf _) AppSt)
performAction _ e = case e of 
  AppDoNothing -> do
    T.modifyState \_ -> {}
    return unit
  AppSearch ws -> do
    liftEff (trace ("searched " ++ ws))
    return unit
```

The compiler says

```
Error at /Users/Angus/code/web/wikit/client/src/Components/App.purs line 30, column 3 - line 31, column 3:
Error in declaration app
Cannot unify # ! with *.
```

Due to my lack of purescript knowledge, I'm having a little difficulty reading this, however a quick google tells me `# !` is an effect kind or something, but It's still a little confusing for me. 

When I change the type too

```purescript
performAction :: T.PerformAction AppPs AppEv (T.Action _ AppSt)
```

I get the error message 

```
No instance found for Control.Monad.Eff.Class.MonadEff (trace :: Debug.Trace.Trace | u21089) (Thermite.Action.Action u21073 {  })
```

So it seems that the `Action` type doesn't support Effects? Is this the result of my incompetence or is this by design?

**Comment by paf31** [comment]
So the first argument to `Action` is a _row_ of effects, not a type constructor. You pass `AppEf _` as the argument, which is `Eff (trace :: Trace) _`. The part you want is `(trace :: Trace)`. So you want:

```purescript
type AppEf = (trace :: Trace)

performAction :: forall e. T.PerformAction AppPs AppEv (T.Action AppEf AppSt)
```

**Comment by AKST** [comment]
Ohhhhhhhh, okay that makes sense, I always thought `(trace :: Trace)` was a thing special to `Eff`, I never really picked up it was an actual record. This answers a few things, thanks.

**Comment by paf31** [comment]
Well, it's a _row_, not a record, but the two are closely related. A record is parameterized by a row of types, where `Eff` is parameterized by a row of _effects_, but the underlying machinery in the type checker is the same.

**Comment by AKST** [comment]
oh right, I guess that's explains the different syntax
