### ISSUE TITLE
Support for inline styles

### ISSUE THREAD

**Issue by passy** [paf31/purescript-thermite#18]
Hey, I hope I not just missed some way of doing this that already exists, but I'd like to use [inline styles](https://facebook.github.io/react/tips/inline-styles.html). This comes with the nice benefit of being able to express your styles in terms of code and running optimizations, dead-code-eliminations etc. on it.

In `purescript-react` the `Style` modifier [accepts arbitrary records](https://github.com/purescript-contrib/purescript-react/blob/dd8f0de48cd04367f57b1dc18c8a7b5c4733366b/src/React/DOM.purs#L87). Could the same be done here?

**Comment by paf31** [comment]
I would like to work on something generic in the style of [Clay](http://hackage.haskell.org/package/clay), which could be implemented in another library and then used here and elsewhere.

If anyone wants to start working on something like that, I'd probably get involved...

**Comment by passy** [comment]
Clay looks amazing indeed! Agreed with the type safety, especially since the keys would be unchecked strings.

But I wonder if a stop gap solution would be better than not supporting it at all until something like Clay comes into existence in PureScript land. :) When changing background images on the fly, for example, it's not possible to express that through static CSS.

**Comment by passy** [comment]
Just quickly checked, to add support for the React attribute, this actually works:

```diff
diff --git a/src/Thermite/Html/Attributes.purs b/src/Thermite/Html/Attributes.purs
index 35027e8..461d2a6 100644
--- a/src/Thermite/Html/Attributes.purs
+++ b/src/Thermite/Html/Attributes.purs
@@ -276,6 +276,9 @@ start = unsafeAttribute "start"
 step :: forall action. String -> Prop action
 step = unsafeAttribute "step"
 
+style :: forall s action. { | s} -> Prop action
+style = unsafeAttribute "style"
+
 tabIndex :: forall action. String -> Prop action
 tabIndex = unsafeAttribute "tabIndex"
```

But I guess I can also use this as local helper function in my project instead.

**Comment by paf31** [comment]
I agree that a solution is needed, but using open records really goes against the goal of this library IMO. It should be straightforward to support this in a library though...

**Comment by passy** [comment]
Okay, that's a totally valid call to make. Thanks for the explanation!

I don't know whether you want to keep this open for future roadmap plans, otherwise feel free to close it. :)

**Comment by paf31** [comment]
Yes, let's keep it open.

**Comment by paf31** [comment]
`purescript-css` might be helpful here /cc @puffnfresh

**Comment by paf31** [comment]
Now that Thermite uses `purescript-react`, I'm going to close this.
