### ISSUE TITLE
State type lost by React

### ISSUE THREAD

**Issue by matthieubulte** [paf31/purescript-thermite#22]
React seems to erase the class of the state object, resulting in failing pattern matches at runtime. For instance, if my state type is the following ADT:
```
data State = Success
           | Error String
```

Then, in the react implementation of `setState`, the new state will be assigned using `assign({}, this._pendingState || this.state, partialState),` which will erase javascript's type information about the state. As a result, the state object won't be an instance of  `Success` or `Error` anymore but just an `Object`, resulting in an error when pattern matching on it.

To bypass this problem, I wrapped my state in another ADT (`data State' = State' State`), which seems to keep the type information of the state and it works then perfectly.

My solution is only a hack and it will probably be a problem for other people too, so we should either find a solution to this type erasure done by react, or we should put it big in the docs that this kind of things happen.

Thanks.

**Comment by paf31** [comment]
I think the state has to be an object in Javascript. I should make that restriction in the types.

**Comment by paf31** [comment]
Fixed in 0.7.1
