### ISSUE TITLE
Passing keys to child components

### ISSUE THREAD

**Issue by farnoy** [paf31/purescript-thermite#27]
I have this issue https://fb.me/react-warning-keys when integrating existing react components (in jsx) with purescript ones.

I've rewritten my `MessageListItem` component to purescript+thermite and rendering it like this:

```jsx
React = require("react")
MessageListItem = require("./MessageListItem")
MessageListItemPurs = require("./MessageListItemPurs").component

module.exports = React.createClass
  render: ->
    <div style={@style}>
      {@props.messages.map (message) ->
        <MessageListItemPurs key={message.id} {...message} />
      }
    </div>

  style:
    padding: 0
    display: "flex"
    flexFlow: "column nowrap"
```

and my `MessageListItemPurs`:

```purs
module MessageListItemPurs where

import Data.Date
import Data.Maybe
import qualified Thermite as T
import qualified Thermite.Html as T
import qualified Thermite.Html.Elements as T
import qualified Thermite.Html.Attributes as A
import qualified Thermite.Action as T
import qualified Thermite.Events as T
import qualified Thermite.Types as T

type Author = { login :: String }
type Props = { body :: String, author :: Author,  timestamp :: String}

render :: T.Render _ Unit Props Unit
render _ _ props _ = T.div' [counter]
  where
  counter :: T.Html _
  counter =
    T.div'
      [ T.div' [
          T.strong' [T.text props.author.login]
        , T.text " - "
        , date (fromString props.timestamp)
        ]
      ]

  date :: Maybe Date -> T.Html _
  date (Just d) = T.code' [T.text (show d)]
  date Nothing = T.text ""

spec :: T.Spec _ Unit Props Unit
spec = T.simpleSpec unit performAction render

component = T.createClass spec

performAction :: T.PerformAction _ Unit Props Unit
performAction _ _ = return unit
```

Tried adding `key :: String` to `Props` but it doesn't affect the compiled code in any way so that parameter doesn't get through to react?

**Comment by paf31** [comment]
Keys aren't supported right now, but it's on the todo list: #20

**Comment by farnoy** [comment]
Alright, I've researched this a bit more and the exact problem is this:

```
React.createElement("div", null, React.createElement("span"))
ReactElement {type: "div", key: null, ref: null, _owner: null, _context: Object…}
React.createElement("div", null, [React.createElement("span")])
flux.entry.js:3044 Warning: Each child in an array or iterator should have a unique "key" prop. Check the React.render call using <div>. See https://fb.me/react-warning-keys for more information.
ReactElement {type: "div", key: null, ref: null, _owner: null, _context: Object…}
```

Passing array to `createElement` requires keys to be present and unique, but semantically, we're doing something different than react. In JSX they use arrays to indicate multiple children of the same type/structure and every other usecase passes arguments to `createElement` like this: `createElement.apply(this, [props, state, children])`. Since thermite uses `[Html _]` everywhere, we always need to provide keys for our elements.

I propose adding a way to specify when to render an array JSX style.

```
render :: T.Render _ Unit Props Unit
render _ _ props _ = T.div' [content]
  where
  content :: T.Html _
  content =
    T.div'
      [ T.div' [
          T.strong [T.text "Bob Loblaw"]
        , T.array $ map (\text -> T.span' [T.text text]) $ range 1 50
        ]
      ]
```

The equivalent in current version:

```
render :: T.Render _ Unit Props Unit
render _ _ props _ = T.div (A.key "0") [content]
  where
  content :: T.Html _
  content =
    T.div (A.key "0")
      [ T.div' (A.key "0") [
          T.strong (A.key "0") [T.text "Bob Loblaw"]
        ] <> array
        ]
      ]
  array :: T.Html _
  array = map (\text -> T.span (A.key text) [T.text text]) $ range 1 50
```

Anyway, I'd like to help implementing it too.

**Comment by felixSchl** [comment]
+1 I would love to see this actioned upon

**Comment by fisx** [comment]
I get strange behavior that may be related to this issue: I have a dynamic list that, when I shrink it, trails old zombie elements in the list position that should be gone.  All other list elements are appropriately moved one up.  When I reload, the list rendering is correct.  Behavior is non-deterministic: in rare cases, it simply works.

It is entirely possible that I am making a stupid mistake, or that the problem is unrelated to this.  Any comments appreciated.

In case you are interested: https://github.com/zerobuzz/vote-button

**Comment by paf31** [comment]
I think this can be handled in `purescript-react` now.
