### ISSUE TITLE
Wishlist: example with webpack

### ISSUE THREAD

**Issue by haf** [paf31/purescript-thermite#32]
This would make it easier to get started with thermite in an existing app. It could showcase a workflow for dealing with purescript packages with webpack. E.g. in my current set up, the app is crashing with:

```
17:42:16.453 TypeError: Prelude['<<<'] is not a function1 bundle.js:928:12
```

Cross-posted https://github.com/ethul/purs-loader/issues/22

**Comment by paf31** [comment]
Does `pulp server` work for you?

**Comment by haf** [comment]
Sure, I've not used it but as long as it's easy to start with.

**Comment by paf31** [comment]
See https://github.com/nwolverson/purescript-thermite-example
