### ISSUE TITLE
Question: combining components with different props

### ISSUE THREAD

**Issue by AlexeyRaga** [paf31/purescript-thermite#41]
Assume I have two components, both stateless (for simplicity), both have their own props and actions:

    -- widget.purs
    widget :: Spec _ _ WidgetProps WidgetAction
    widget = simpleSpec performWidgetAction renderWidget

Now I want to add the widget into some sort of a panel:

    -- panel.purs   
    panel :: Spec _ _ PanelProps PanelAction
    panel = simpleSpec performPanelAction renderPanel

It is OK for a panel to "know" about the widget (and other components inside it), but I want the widget to be completely unaware of the panel so it can be composed into other things.

I also want the panel to "react" on what happens in the widget. Should it be handling `WidgetAction` or should `WidgetProps` declare some sort of a callback - I don't know what is be the better way, and it is also a part of my question.

Is there an example showing how to compose two components with different props and actions so one "subscribes" to the "events" of another?
Or what is the way to do it with `purescript-react`/`thermite`?

Regards,
Alexey.

**Comment by paf31** [comment]
Thermite doesn't do much with `props`, only state. Right now, you can read `props` in render, or convert to a React component spec, and do stuff with the `props` there before finally converting to a component class.

The tricky thing is that `props` aren't as nicely composable as the state from Thermite's point of view, in the sense that the parent is responsible for updating `props`, not the current component. On the other hand, we can share parts of state between parent and child easily.

**Comment by AlexeyRaga** [comment]
Yes, I see that I could manage it through state, but React itself is moving more and more away from the concept of stateful components, and the current version even introduces a new syntax:

    var Aquarium = (props) => {
      var fish = getFish(props.species);
      return <Tank>{fish}</Tank>;
    };

which is actually a function from props to component, so I thought that maybe there is a way to embrace props rather than fighting them...

The fact that the parent is responsible for providing props and not the current component corresponds to the fact that the caller is responsible for providing function arguments and not the function itself. Not sure if it should be a problem for composition.

**Comment by paf31** [comment]
This is probably relevant: https://github.com/purescript-contrib/purescript-react/pull/52

**Comment by AlexeyRaga** [comment]
Oh, thank you! I will definitely check it out. Does it still work with the latest `purescript-thermite`?

**Comment by paf31** [comment]
Yes, I've updated Thermite to use the latest version.

**Comment by AlexeyRaga** [comment]
Thanks a lot! I'll close this issue and give it a go.
