### ISSUE TITLE
Handling a single optional child with Maybe

### ISSUE THREAD

**Issue by emk** [paf31/purescript-thermite#45]
I've spent some time coding with Elm, Halogen and Thermite, and I'm really delighted with Thermite's simplicity and flexibility. It hits a sweet spot for me.

Right now, Thermite handles single child elements which are always present (using `focus`), and lists of 0 to N child elements (using `foreach`). But I couldn't find any way to handle a single child element which may or may not be present.

What I would love to have is a function with the signature:

```purs
maybeSpec :: forall eff props state action.
  T.Spec eff state props action ->
  T.Spec eff (Maybe state) props action
```

I believe this could be implemented inside Thermite as:

```purs
maybeSpec (T.Spec spec) = T.Spec
  { performAction: performAction
  , render: render
  }
  where

  performAction :: T.PerformAction eff (Maybe state) props action
  performAction a p Nothing k = pure unit
  performAction a p (Just st) k = spec.performAction a p st k

  render :: T.Render state2 props action2
  render k p Nothing = []
  render k p (Just st) = spec.render k p st
```

But the `T.Spec` constructor is private, and so if we need to implement this outside of Thermite, it gets slightly tricky:

```purs
maybeSpec spec = T.withState makeSpec
  where
    makeSpec Nothing = T.simpleSpec T.defaultPerformAction T.defaultRender
    makeSpec (Just state) = T.focus justLens id spec

    justLens :: LensP (Maybe state) state
    justLens = lens Unsafe.fromJust (\_ v -> Just v)
```

Here is some sample code showing how this might be used:

```purs
type State = { player :: Maybe VideoPlayer.State }
data Action = PlayerAction VideoPlayer.Action

_PlayerAction :: PrismP Action VideoPlayer.Action
_PlayerAction = prism PlayerAction \pa ->
  case pa of
    PlayerAction act -> Right act

_player :: LensP State (Maybe VideoPlayer.State)
_player = lens _.player (_ { player = _ })

app :: forall props. T.Spec AppEffects State props Action
app
  = T.simpleSpec performAction render
  <> T.focus _player _PlayerAction (maybeSpec VideoPlayer.videoPlayer)
```

If you think that it would be worth supporting something like `maybeSpec`, I'm happy to submit a PR (and to rename it to a better name if you can think of one).

And thank you very much for Thermite! I'm finding that it's the most productive of all the React-style strongly-typed libraries that I've tried.

**Comment by paf31** [comment]
I'm glad you're enjoying using the library :smile: 

I think a slightly more general approach is

```purescript
prismSpec :: forall eff props state1 state2 action.
  PrismP state1 state2
  T.Spec eff state1 props action ->
  T.Spec eff state2 props action
```

where we show the child component only if the prism matches its constructor. I think this allows us to glue together optional components to make things like tabs, and the state doesn't have to look like `Maybe s` for some `s`.

Come to think of it, the ability to apply an `IsoP` might also be nice, but that's a job for another PR.

Anyway, a PR for either `maybeSpec` or `prismSpec` (possibly after renaming) would be fantastic.

**Comment by emk** [comment]
Thank you for your quick response! Using prisms is a great idea.

I considered naming `prismSpec` several things that sounded better alongside `focus`, including `refract` and `split`. I eventually went with `split`, because it looked slightly less mysterious in code, but I'm not overly attached to the name.

This works nicely in my code:

```purs
hello :: forall props. T.Spec AppEffects State props Action
hello
  = T.simpleSpec performAction render
  <> T.focus _player _PlayerAction (T.split _Just VideoPlayer.videoPlayer)
  <> T.focus _player _PlayerAction (T.split _Just testControls)
```

Thermite is proving to be a highly productive library for me so far, probably because of some combination of the following:

- React itself is a high-quality, production-grade library.
- Purescript is both expressive enough to apply major functional programming ideas, and pragmatic enough to interface trivially with JavaScript.
- Thermite is a thin, easy-to-understand wrapper over React. And the decision to use lens and prisms makes it very easy to work flexibly with nested state without needing to wrangle heavy, type-level machinery.

**Comment by paf31** [comment]
> Thermite is proving to be a highly productive library for me so far

Excellent! Any feedback is very welcome, especially since I'm thinking about using Thermite in the PureScript book once it's tested enough.
