### ISSUE TITLE
purescript-react only contains react as a dev dependency

### ISSUE THREAD

**Issue by joelgrus** [paf31/purescript-thermite#47]
looks like it got moved into dev dependencies here:

https://github.com/purescript-contrib/purescript-react/commit/2c040de6409ba5a6b5bd687446e582a181744a35

this means the "building" instructions here don't quite work, because they don't install react. the example works if I manually `pulp dep install react` before building.

not sure if solution is to add react to the bower.json here? or to move it to dependencies over there?

**Comment by paf31** [comment]
React will change to be an NPM dependency in the next release, so it will be tracked separately until we get some kind of PureScript package manager.
