### ISSUE TITLE
Asynchronous updates overwrite entire application state

### ISSUE THREAD

**Issue by spencerjanssen** [paf31/purescript-thermite#48]
Imagine we have PerformActions similar to:

    performA SlowEvent _ state _ update = timeoutSeconds 10 $ update $ state {foo = "blah"}

    performB CountUp _ state _ update = update $ state {counter = state.counter + 1}

Say `SlowEvent` happens and then, before the 10 second timeout is finished, `CountUp` happens.  Briefly we have a state where the counter has changed, but that change is eventually lost when `SlowEvent` completes.  Even if `performA` and `performB` use `focus` to view different parts of the state we lose all updates in between an asynchronous call.

This example is contrived of course, but it isn't hard to imagine this happening in real applications that call JSON APIs to fetch data.

**Comment by paf31** [comment]
Yes, Thermite doesn't deal with these kinds of races right now. Perhaps the solution is to make the state have type `Eff _ state` so that it can be read _inside_ the timeout handler.

**Comment by spencerjanssen** [comment]
That seems like a reasonable change and is certainly the most simple.  One drawback is that pure `PerformAction`s become a little uglier.  Perhaps at the same time we'll want something like:

    type PureAction state props action = action -> props -> state -> Maybe state
    liftPureAction :: forall state props action eff. PureAction state props action -> PerformAction eff state props action

Where `liftPureAction` does the natural but repetitive state reading and writing.

**Comment by spencerjanssen** [comment]
I started changing Thermite to pass an `Eff _ state` rather than the state itself and hit a snag with `foreach`.  The underlying list may no longer have a value at the particular index, meaning we won't have a state to return.

**Comment by paf31** [comment]
I've added a PR with a slightly different approach --> #50.

**Comment by paf31** [comment]
Fixed in 0.13.0
