### ISSUE TITLE
Alternatives to `unsafeCoerce` for event handlers?

### ISSUE THREAD

**Issue by danse** [paf31/purescript-thermite#49]
In the demo project, i see that `unsafeCoerce` is used in every event handler where there is the need to access event data. Instinctively i feel like looking for a better alternative, is there any?

**Comment by danse** [comment]
In one case i think that i can import `target` from `DOM.Event.Event` and then use:

    \ e -> (target e).value

For example. Not yet sure about what to do when i want to retrieve the key code

**Comment by paf31** [comment]
Thermite doesn't provide any functionality here, so the examples do the simplest, unsafest thing. It should be possible to drop in any library which provides FFI bindings to DOM events though.

**Comment by danse** [comment]
Alright. `DOM.DOM.Event` already provides some utilities, like `target`, but the Event returned here is different, it is [this one](http://pursuit.purescript.org/packages/purescript-react/0.5.0/docs/React#t:Event) from React. Maybe React could adopt DOM events, in order to reuse existing definitions

**Comment by paf31** [comment]
I think that's the right solution. We should handle this inside `purescript-react` then.

**Comment by danse** [comment]
Alright i wrote a reminder issue on React, it does not seem urgent anyway
