### ISSUE TITLE
Can't get any examples working

### ISSUE THREAD

**Issue by mrkgnao** [paf31/purescript-thermite#63]
I'm new to PureScript and Thermite. I'm running a fresh Arch install (I set it up yesterday).

I tried running the "Actions" lesson from Try Thermite by doing the following:

* `mkdir thermite-test && cd thermite-test`
* `pulp init`
*  `bower i purescript-thermite --save`
* copying and pasting the code from that lesson into `src/Main.purs`
* `pulp build`

but I get a huge bunch of errors, mostly to do with `unexpected "qualified"`statements in the dependencies like `Data.Lazy`. 

I think this may have to do with some changes in PureScript syntax, since when I do the `bower` installation, I'm asked to choose between `Prelude` versions `0.1.5` and `1.0.0` or something similar because of a dependency conflict.

Any ideas?

**Comment by paf31** [comment]
What version of the compiler are you using?

I would recommend waiting a couple of days, at which point I hope to have a v1.0.0 release of Thermite which will work with the latest 0.9.1 compiler.

**Comment by mrkgnao** [comment]
I just downloaded the latest versions of everything from npm today.

**Comment by paf31** [comment]
The released version of Thermite doesn't work with 0.9.1 yet. You could try building `master`.

**Comment by mrkgnao** [comment]
Sure, I can try that.

**Comment by mrkgnao** [comment]
@paf31: `master` builds fine, but doing an `npm test` and opening `html/index.html` gives me a near-empty page with nothing but the "Fork me on GitHub" banner.

[html/index.html source](http://lpaste.net/2378050609279401984)

**Comment by paf31** [comment]
Do you see any errors in the console?

**Comment by mrkgnao** [comment]
Never mind, I just forgot to do an `npm install`. The example renders perfectly now.

Thanks for the help. :smile:
