### ISSUE TITLE
Missing hello world / template?

### ISSUE THREAD

**Issue by MaiaVictor** [paf31/purescript-thermite#64]
The ["hello world"](http://lpaste.net/168958) explained on the README doesn't compile as it seems to be missing an import to body. The examples at [Try Thermite](http://paf31.github.io/try-thermite/?gist=0bd459f479987580e833) depend on `Thermite.Try`, so, I think they're not supposed to be used as a template for a new project too. What is a proper Thermite Hello World that I can use as a template for new Thermite projects?

**Comment by kRITZCREEK** [comment]
What about the project inside the ´test/` directory? Does that work?

**Comment by paf31** [comment]
Yes, you should look at the test project. I omitted `body` from the README, since it's boilerplate code which isn't specific to Thermite.

**Comment by MaiaVictor** [comment]
Gotcha, thanks.

**Comment by MaiaVictor** [comment]
I think that isn't the best hello world, actually. It doesn't work as a simple template I can just start hacking in. For one, there are many files and components which obviously aren't part of my app, so I have to remove them. But of course I don't know what I can safely remove because, by definition, I'm a newcomer doing that exactly to learn about the lib. A template should basically be just have the skeleton with no specific component.

```
import DOM (DOM) as DOM
import DOM.HTML (window) as DOM
import DOM.HTML.Types (htmlDocumentToParentNode) as DOM
import DOM.HTML.Window (document) as DOM
import DOM.Node.ParentNode (querySelector) as DOM
import React as R
import ReactDOM as RDOM
import Thermite as T
```

The sheer amount of DOM, React imports - do I need all that anytime I create a new app? The library should hide that from me.

```
main :: Eff (dom :: DOM.DOM) Unit
main = void do
  let component = T.createClass taskList initialTaskListState
  document <- DOM.window >>= DOM.document
  container <- unsafePartial (fromJust <<< toMaybe <$> DOM.querySelector "#container" (DOM.htmlDocumentToParentNode document))
  RDOM.render (R.createFactory component {}) container
```

Then, WTF again. What is that even doing? A newcomer having Thermite as his first PureScript experience won't have an idea what that is doing, and it shouldn't, because the purpose of the lib is to abstract always all the DOM manipulation!

I think something like that would be ideal:

```
import Thermite.Template -- or something like that

myApp :: ...
myApp = ... here I write stuff ...

main :: CommonThermiteApp
main = defaultWebApp myApp
```

With `defaultWebApp` doing whatever that thing is doing on the example. That'd reduce a lot the entry barrier for newcomers, I think. As of now, I can't do anything other than give up of learning Thermite to learn the DOM and React libs, so I can come back here and I understand what that code is doing. Which shouldn't be the case! I'd write that Template myself, if only I knew.

**Comment by paf31** [comment]
You're probably right. PRs are welcome for both examples, and adding the boilerplate code. Note that Try Thermite already includes the boilerplate in the `Thermite.Try` module.

**Comment by MaiaVictor** [comment]
I am going through the longer path, reading and learning as much as I can about the core libraries. When/if I get comfortable enough with DOM, Aff, and so on, I might come back and write a friendlier template.
