### ISSUE TITLE
Asynchronous handlers closing over state?

### ISSUE THREAD

**Issue by BartAdv** [paf31/purescript-thermite#74]
Hi!

So I've fired Try Purescript! with Async lesson, to just have the general idea what Thermite provides in terms of asynchronous handlers: http://try.purescript.org/?gist=e6a2142e872dbc7e6557a78a55f03589&backend=thermite&session=68d15d4b-2a9b-f16d-2c1e-1a6e932736fa

The original example is rather simple, so I wanted to add something more to make it more "real world":

```
performAction :: T.PerformAction _ State _ Action
performAction Increment _ _ = void do
  T.modifyState \state -> state + 10
  lift (delay 500)
  T.modifyState \state -> state + 1
performAction Decrement _ _ = void do
  lift (delay 500)
  T.modifyState \state -> state - 1
```

This emulates the common pattern in which I'd set some flag in the state denoting in progress, then perform a request, and when response arrives I'd reset that flag.

With this example, when clicking fast enough, it's visible that the value is first incremented by 10, then goes back by 10, it's incremented by 1, goes back again, and after a while of such changes, it may arrive at non-correct value.

**Comment by paf31** [comment]
Thanks, I have a fix for this, I'll put up a PR soon.
