### ISSUE TITLE
Routing and actions/effects while switching views

### ISSUE THREAD

**Issue by sudhirvkumar** [paf31/purescript-thermite#78]
@paf31 Any plans or ideas for implementing Routing?

We are loving Thermite and have built a mobile app using react native and in the final stages of going live in the app store. Thanks for your hard work.

The only issue we are facing right now is we are having to have a single `State` which is shared with every single Spec. When we want to change the view. We need access to the whole State.

The reason being

1. Need to set the value to the Current Page / View
2. Load data necessary for the next view.

Any idea how to handle this?

We used the idea from your Slides https://github.com/paf31/codemesh2016/blob/master/thermite/src/Main.purs#L65

Once we figure this out... then we will be really happy as we will be able to build components which has State only relevant to itself instead of sharing the whole State across all Components.

Rough idea I have come up with is as follows.

1. Define all the Routes as ADT and a function which runs initial effects when this function is called with the Route.
2. FFI code with Route stored as a closure inside a function. Another function to change the Route and a list of subscribers.
3. Setup a subscription in the main component which listens to the Route change. When the route changes dispatch an action. like your timer example. https://github.com/paf31/codemesh2016/blob/master/thermite/src/Main.purs#L755
4. In this action we use the route and call the routing function which changes the `Current Page/View` and also runs the initial effects/actions for that route.
5. In the Render function of any Spec, we should be able to call the `changeRoute` function which changes the route.

I hope my idea makes sense. If there is any simple way of handling routing. let me know!

This only solves the React Native issues... need to figure out the url change and route naccordingly. If this is implemented then it can be adapted to web too, like in `purescript-pux`

Help is appreciated. Thanks in advance!

**Comment by paf31** [comment]
I don't have any plans to add routing to Thermite, but it seems like the sort of thing which could be implemented in a separate library. Or you could use something like `slamdata/purescript-routing` perhaps.

**Comment by sudhirvkumar** [comment]
@paf31 thanks `slamdata/purescript-routing` is really useful. That is specific for Web and URL Hash. I guess I can use that to build my own routing library for React Native. Thanks for your reply.
