### ISSUE TITLE
Server Side Rendering in Thermite

### ISSUE THREAD

**Issue by sudhirvkumar** [paf31/purescript-thermite#79]
How can we reliable render the pages after loading the data from database and then render that to string and return to the browser?

https://github.com/purescript-contrib/purescript-react-dom/blob/master/src/ReactDOM.purs#L32

I can use the `renderToString` from the ReactDOM package.

The issue here is... using CoTransform and Aff and still being able to render that to string and also not making major changes to the code for server side rendering...

Right now we are getting "Loading..." message and the string doesn't contain data which is loaded.

@paf31 Help is appreciated. Thanks in Advance!

**Comment by paf31** [comment]
I don't understand. What do `CoTransform` and `Aff` have to do with server-side rendering? This doesn't seem related to Thermite.

> Right now we are getting "Loading..." message and the string doesn't contain data which is loaded.

Which loading message?

**Comment by sudhirvkumar** [comment]
Can you point me to some examples where I can check Server Side rendering with thermite? Thanks. I hope there is some example somewhere with some data loading in the initial stage.

**Comment by paf31** [comment]
No, sorry, I don't have any examples.

**Comment by paf31** [comment]
I'm going to close this, because it's not something which is specific to Thermite, as far as I can tell. Maybe someone can help if you post on `purescript-react`.

**Comment by sudhirvkumar** [comment]
@paf31 thanks for your reply. I will try to figure it out and if I am successful will let you know.
