### ISSUE TITLE
ReactDOM failed to load

### ISSUE THREAD

**Issue by baig** [paf31/purescript-thermite#81]
Opening the `index.html` file in the chromium browser throws the following error:

```
Uncaught TypeError: Cannot read property 'create' of undefined
    at PS.ReactDOM (index.js:2844)
    at index.js:2846
```

**Comment by paf31** [comment]
Is this using PS 0.10.6? If so, it's probably due to a compiler bug which was fixed in the 0.10.7 release (which was released today).

**Comment by baig** [comment]
Yes. `psc --version` tells me it's `0.10.6`

**Comment by baig** [comment]
works with `0.10.7`
