### ISSUE TITLE
Remove DOM dependency

### ISSUE THREAD

**Issue by jvliwanag** [paf31/purescript-thermite#93]
Might it be better to have thermite depend solely on purescript-react, without purescript-react-dom and purescript-dom? This way, upgrading will be simpler and users of react native won't need to have the DOM stuff around.

Wanted to upgrade thermite to use purescript-react-5.0.0 when I ran into this.

**Comment by jvliwanag** [comment]
Alternatively, create purescript-thermite-dom as a separate package?

**Comment by dwhitney** [comment]
+1 for this. I'd be in favor of `purescript-thermite-dom` -- had to remove it my fork to get Thermite working with React Native. I'd be happy to do a PR if @paf31 is good with this.

**Comment by jvliwanag** [comment]
@dwhitney interestingly, had to make only a few changes to make this work with react native. See #94 which works with react native. But of course, moving the dom stuff to a separate dep would be preferable.

**Comment by dwhitney** [comment]
Yeah I've got a branch in my fork doing the same

**Comment by athanclark** [comment]
Hey yall, sorry for being out of the loop - I'll be happy to break-off dom-related libraries for mounting to a separate package. React-native is definitely a killer feature for this project.

**Comment by dwhitney** [comment]
I've moved onto react-basic, and I've made quite a bit of progress putting
together a React Native library for it. I think it should be ready for use
in a couple of weeks:
https://github.com/dwhitney/purescript-react-basic-native

**Comment by athanclark** [comment]
@dwhitney shoot, I guess I'm a bit too late then :) sorry about that. I'd love to check out your bindings in the future, but if anyone runs into the same problem, I've made the adjustment. Thank you again for bringing this up!
